-- ============================================================================
-- ALL COUNTRIES FROM REST COUNTRIES API
-- Auto-generated script to insert all world countries
-- Total countries: 245
-- Generated: 2025-10-19
-- Exchange rates from: Frankfurter API (European Central Bank)
-- ============================================================================

-- First, let's add all currencies with LIVE exchange rates
-- Source: https://api.frankfurter.app/latest?from=USD
-- Last updated: 2025-10-17
INSERT INTO stripe_currency_rates (currency_code, currency_name, rate_to_usd) VALUES
('AED', 'UAE Dirham', 1.000000),
('ARS', 'Argentine Peso', 1.000000),
('AUD', 'Australian Dollar', 0.649140),
('BRL', 'Brazilian Real', 0.184077),
('CAD', 'Canadian Dollar', 0.712555),
('CHF', 'Swiss Franc', 1.261861),
('CLP', 'Chilean Peso', 1.000000),
('CNY', 'Chinese Yuan', 0.140404),
('COP', 'Colombian Peso', 1.000000),
('CZK', 'Czech Koruna', 0.048054),
('DKK', 'Danish Krone', 0.156394),
('EUR', 'Euro', 1.168101),
('GBP', 'British Pound', 1.343418),
('HKD', 'Hong Kong Dollar', 0.128742),
('HUF', 'Hungarian Forint', 0.002997),
('IDR', 'Indonesian Rupiah', 0.00006000),
('ILS', 'Israeli Shekel', 0.302462),
('INR', 'Indian Rupee', 0.011364),
('JPY', 'Japanese Yen', 0.006648),
('KRW', 'South Korean Won', 0.00070400),
('KWD', 'Kuwaiti Dinar', 1.000000),
('MXN', 'Mexican Peso', 0.054318),
('MYR', 'Malaysian Ringgit', 0.236630),
('NOK', 'Norwegian Krone', 0.099589),
('NZD', 'New Zealand Dollar', 0.573164),
('PEN', 'Peruvian Sol', 1.000000),
('PHP', 'Philippine Peso', 0.017195),
('PLN', 'Polish Zloty', 0.275171),
('QAR', 'Qatari Riyal', 1.000000),
('RUB', 'Russian Ruble', 1.000000),
('SAR', 'Saudi Riyal', 1.000000),
('SEK', 'Swedish Krona', 0.105902),
('SGD', 'Singapore Dollar', 0.772320),
('THB', 'Thai Baht', 0.030520),
('TRY', 'Turkish Lira', 0.023838),
('USD', 'US Dollar', 1.000000),
('VND', 'Vietnamese Dong', 1.000000),
('ZAR', 'South African Rand', 0.057542)
ON CONFLICT (currency_code) DO UPDATE SET
    rate_to_usd = EXCLUDED.rate_to_usd,
    last_updated = CURRENT_TIMESTAMP;


-- TIER 1 - Emerging Markets (8.99$ Pro / 9.99$ Elite)
-- Total: 182 countries
INSERT INTO stripe_country_tiers (country_code, country_name, tier_level, currency_code, currency_symbol) VALUES
('BJ', 'Benin', 1, 'USD', '$'),
('FK', 'Falkland Islands', 1, 'USD', '$'),
('GH', 'Ghana', 1, 'USD', '$'),
('CU', 'Cuba', 1, 'USD', '$'),
('AR', 'Argentina', 1, 'ARS', '$'),
('SV', 'El Salvador', 1, 'USD', '$'),
('UZ', 'Uzbekistan', 1, 'USD', '$'),
('BZ', 'Belize', 1, 'USD', '$'),
('CI', 'Ivory Coast', 1, 'USD', '$'),
('MP', 'Northern Mariana Islands', 1, 'USD', '$'),
('CG', 'Republic of the Congo', 1, 'USD', '$'),
('BD', 'Bangladesh', 1, 'USD', '$'),
('PW', 'Palau', 1, 'USD', '$'),
('AF', 'Afghanistan', 1, 'USD', '$'),
('ET', 'Ethiopia', 1, 'USD', '$'),
('NC', 'New Caledonia', 1, 'USD', '$'),
('TM', 'Turkmenistan', 1, 'USD', '$'),
('MS', 'Montserrat', 1, 'USD', '$'),
('BG', 'Bulgaria', 1, 'EUR', '€'),
('LC', 'Saint Lucia', 1, 'USD', '$'),
('SN', 'Senegal', 1, 'USD', '$'),
('UY', 'Uruguay', 1, 'USD', '$'),
('GW', 'Guinea-Bissau', 1, 'USD', '$'),
('PH', 'Philippines', 1, 'PHP', '₱'),
('TZ', 'Tanzania', 1, 'USD', '$'),
('IM', 'Isle of Man', 1, 'GBP', '£'),
('SD', 'Sudan', 1, 'USD', '$'),
('SL', 'Sierra Leone', 1, 'USD', '$'),
('TD', 'Chad', 1, 'USD', '$'),
('VU', 'Vanuatu', 1, 'USD', '$'),
('RW', 'Rwanda', 1, 'USD', '$'),
('TG', 'Togo', 1, 'USD', '$'),
('KM', 'Comoros', 1, 'USD', '$'),
('XK', 'Kosovo', 1, 'EUR', '€'),
('KG', 'Kyrgyzstan', 1, 'USD', '$'),
('CV', 'Cape Verde', 1, 'USD', '$'),
('VE', 'Venezuela', 1, 'USD', '$'),
('PN', 'Pitcairn Islands', 1, 'USD', '$'),
('YT', 'Mayotte', 1, 'EUR', '€'),
('TL', 'Timor-Leste', 1, 'USD', '$'),
('SB', 'Solomon Islands', 1, 'USD', '$'),
('PM', 'Saint Pierre and Miquelon', 1, 'EUR', '€'),
('EC', 'Ecuador', 1, 'USD', '$'),
('CF', 'Central African Republic', 1, 'USD', '$'),
('TO', 'Tonga', 1, 'USD', '$'),
('KN', 'Saint Kitts and Nevis', 1, 'USD', '$'),
('NG', 'Nigeria', 1, 'USD', '$'),
('NU', 'Niue', 1, 'USD', '$'),
('BQ', 'Caribbean Netherlands', 1, 'USD', '$'),
('WF', 'Wallis and Futuna', 1, 'USD', '$'),
('GT', 'Guatemala', 1, 'USD', '$'),
('TN', 'Tunisia', 1, 'USD', '$'),
('BT', 'Bhutan', 1, 'USD', '$'),
('MO', 'Macau', 1, 'USD', '$'),
('SH', 'Saint Helena, Ascension and Tristan da Cunha', 1, 'GBP', '£'),
('WS', 'Samoa', 1, 'USD', '$'),
('TJ', 'Tajikistan', 1, 'USD', '$'),
('EH', 'Western Sahara', 1, 'USD', '$'),
('SO', 'Somalia', 1, 'USD', '$'),
('BL', 'Saint Barthélemy', 1, 'EUR', '€'),
('GG', 'Guernsey', 1, 'GBP', '£'),
('TC', 'Turks and Caicos Islands', 1, 'USD', '$'),
('LS', 'Lesotho', 1, 'USD', '$'),
('JM', 'Jamaica', 1, 'USD', '$'),
('SZ', 'Eswatini', 1, 'USD', '$'),
('GA', 'Gabon', 1, 'USD', '$'),
('KH', 'Cambodia', 1, 'USD', '$'),
('FM', 'Micronesia', 1, 'USD', '$'),
('KP', 'North Korea', 1, 'USD', '$'),
('GQ', 'Equatorial Guinea', 1, 'USD', '$'),
('GL', 'Greenland', 1, 'USD', '$'),
('MX', 'Mexico', 1, 'MXN', '$'),
('BR', 'Brazil', 1, 'BRL', 'R$'),
('NR', 'Nauru', 1, 'AUD', '$'),
('IR', 'Iran', 1, 'USD', '$'),
('AO', 'Angola', 1, 'USD', '$'),
('AW', 'Aruba', 1, 'USD', '$'),
('CC', 'Cocos (Keeling) Islands', 1, 'AUD', '$'),
('MM', 'Myanmar', 1, 'USD', '$'),
('EG', 'Egypt', 1, 'USD', '$'),
('BW', 'Botswana', 1, 'USD', '$'),
('RE', 'Réunion', 1, 'EUR', '€'),
('LR', 'Liberia', 1, 'USD', '$'),
('AI', 'Anguilla', 1, 'USD', '$'),
('AL', 'Albania', 1, 'EUR', '€'),
('CW', 'Curaçao', 1, 'USD', '$'),
('ZM', 'Zambia', 1, 'USD', '$'),
('ST', 'São Tomé and Príncipe', 1, 'USD', '$'),
('BS', 'Bahamas', 1, 'USD', '$'),
('AS', 'American Samoa', 1, 'USD', '$'),
('BO', 'Bolivia', 1, 'USD', '$'),
('IO', 'British Indian Ocean Territory', 1, 'USD', '$'),
('ER', 'Eritrea', 1, 'USD', '$'),
('ML', 'Mali', 1, 'USD', '$'),
('CD', 'DR Congo', 1, 'USD', '$'),
('LY', 'Libya', 1, 'USD', '$'),
('ME', 'Montenegro', 1, 'EUR', '€'),
('PY', 'Paraguay', 1, 'USD', '$'),
('PE', 'Peru', 1, 'PEN', 'S/'),
('BI', 'Burundi', 1, 'USD', '$'),
('LA', 'Laos', 1, 'USD', '$'),
('SS', 'South Sudan', 1, 'USD', '$'),
('KY', 'Cayman Islands', 1, 'USD', '$'),
('MK', 'North Macedonia', 1, 'EUR', '€'),
('MA', 'Morocco', 1, 'USD', '$'),
('AX', 'Åland Islands', 1, 'EUR', '€'),
('GN', 'Guinea', 1, 'USD', '$'),
('NI', 'Nicaragua', 1, 'USD', '$'),
('GP', 'Guadeloupe', 1, 'EUR', '€'),
('LK', 'Sri Lanka', 1, 'USD', '$'),
('CN', 'China', 1, 'CNY', '¥'),
('MH', 'Marshall Islands', 1, 'USD', '$'),
('VC', 'Saint Vincent and the Grenadines', 1, 'USD', '$'),
('SC', 'Seychelles', 1, 'USD', '$'),
('DO', 'Dominican Republic', 1, 'USD', '$'),
('ID', 'Indonesia', 1, 'IDR', 'Rp'),
('MW', 'Malawi', 1, 'USD', '$'),
('CM', 'Cameroon', 1, 'USD', '$'),
('MG', 'Madagascar', 1, 'USD', '$'),
('KI', 'Kiribati', 1, 'AUD', '$'),
('FJ', 'Fiji', 1, 'USD', '$'),
('PF', 'French Polynesia', 1, 'USD', '$'),
('PK', 'Pakistan', 1, 'USD', '$'),
('FO', 'Faroe Islands', 1, 'EUR', '€'),
('SR', 'Suriname', 1, 'USD', '$'),
('DJ', 'Djibouti', 1, 'USD', '$'),
('GM', 'Gambia', 1, 'USD', '$'),
('MN', 'Mongolia', 1, 'USD', '$'),
('ZW', 'Zimbabwe', 1, 'USD', '$'),
('HT', 'Haiti', 1, 'USD', '$'),
('RO', 'Romania', 1, 'EUR', '€'),
('CR', 'Costa Rica', 1, 'USD', '$'),
('HR', 'Croatia', 1, 'EUR', '€'),
('VN', 'Vietnam', 1, 'VND', '₫'),
('NF', 'Norfolk Island', 1, 'AUD', '$'),
('LI', 'Liechtenstein', 1, 'CHF', 'Fr'),
('MC', 'Monaco', 1, 'EUR', '€'),
('PR', 'Puerto Rico', 1, 'USD', '$'),
('TV', 'Tuvalu', 1, 'AUD', '$'),
('GF', 'French Guiana', 1, 'EUR', '€'),
('MF', 'Saint Martin', 1, 'EUR', '€'),
('MU', 'Mauritius', 1, 'USD', '$'),
('PG', 'Papua New Guinea', 1, 'USD', '$'),
('KZ', 'Kazakhstan', 1, 'USD', '$'),
('MY', 'Malaysia', 1, 'MYR', 'RM'),
('UG', 'Uganda', 1, 'USD', '$'),
('BF', 'Burkina Faso', 1, 'USD', '$'),
('GD', 'Grenada', 1, 'USD', '$'),
('CK', 'Cook Islands', 1, 'USD', '$'),
('MV', 'Maldives', 1, 'USD', '$'),
('VI', 'United States Virgin Islands', 1, 'USD', '$'),
('JE', 'Jersey', 1, 'GBP', '£'),
('MQ', 'Martinique', 1, 'EUR', '€'),
('VG', 'British Virgin Islands', 1, 'USD', '$'),
('AG', 'Antigua and Barbuda', 1, 'USD', '$'),
('PA', 'Panama', 1, 'USD', '$'),
('TH', 'Thailand', 1, 'THB', '฿'),
('DZ', 'Algeria', 1, 'USD', '$'),
('MZ', 'Mozambique', 1, 'USD', '$'),
('NA', 'Namibia', 1, 'USD', '$'),
('BB', 'Barbados', 1, 'USD', '$'),
('SJ', 'Svalbard and Jan Mayen', 1, 'EUR', '€'),
('HN', 'Honduras', 1, 'USD', '$'),
('UM', 'United States Minor Outlying Islands', 1, 'USD', '$'),
('GU', 'Guam', 1, 'USD', '$'),
('SX', 'Sint Maarten', 1, 'USD', '$'),
('BM', 'Bermuda', 1, 'USD', '$'),
('BA', 'Bosnia and Herzegovina', 1, 'EUR', '€'),
('KE', 'Kenya', 1, 'USD', '$'),
('TK', 'Tokelau', 1, 'USD', '$'),
('GY', 'Guyana', 1, 'USD', '$'),
('NP', 'Nepal', 1, 'USD', '$'),
('IN', 'India', 1, 'INR', '₹'),
('TT', 'Trinidad and Tobago', 1, 'USD', '$'),
('DM', 'Dominica', 1, 'USD', '$'),
('RS', 'Serbia', 1, 'EUR', '€'),
('NE', 'Niger', 1, 'USD', '$'),
('CX', 'Christmas Island', 1, 'AUD', '$'),
('CO', 'Colombia', 1, 'COP', '$'),
('PL', 'Poland', 1, 'PLN', 'zł'),
('BN', 'Brunei', 1, 'USD', '$'),
('MR', 'Mauritania', 1, 'USD', '$')
ON CONFLICT (country_code) DO UPDATE SET
    country_name = EXCLUDED.country_name,
    tier_level = EXCLUDED.tier_level,
    currency_code = EXCLUDED.currency_code,
    currency_symbol = EXCLUDED.currency_symbol,
    updated_at = CURRENT_TIMESTAMP;

-- TIER 2 - Intermediate Markets (10.99$ Pro / 15.99$ Elite)
-- Total: 34 countries
INSERT INTO stripe_country_tiers (country_code, country_name, tier_level, currency_code, currency_symbol) VALUES
('LT', 'Lithuania', 2, 'EUR', '€'),
('CL', 'Chile', 2, 'CLP', '$'),
('GE', 'Georgia', 2, 'USD', '$'),
('CY', 'Cyprus', 2, 'EUR', '€'),
('AD', 'Andorra', 2, 'EUR', '€'),
('LV', 'Latvia', 2, 'EUR', '€'),
('JO', 'Jordan', 2, 'USD', '$'),
('PS', 'Palestine', 2, 'USD', '$'),
('MD', 'Moldova', 2, 'EUR', '€'),
('MT', 'Malta', 2, 'EUR', '€'),
('GR', 'Greece', 2, 'EUR', '€'),
('CZ', 'Czechia', 2, 'CZK', 'Kč'),
('SM', 'San Marino', 2, 'EUR', '€'),
('IL', 'Israel', 2, 'ILS', '₪'),
('RU', 'Russia', 2, 'RUB', '₽'),
('AZ', 'Azerbaijan', 2, 'USD', '$'),
('SA', 'Saudi Arabia', 2, 'SAR', 'SR'),
('VA', 'Vatican City', 2, 'EUR', '€'),
('SY', 'Syria', 2, 'USD', '$'),
('SK', 'Slovakia', 2, 'EUR', '€'),
('EE', 'Estonia', 2, 'EUR', '€'),
('HU', 'Hungary', 2, 'HUF', 'Ft'),
('LB', 'Lebanon', 2, 'USD', '$'),
('BH', 'Bahrain', 2, 'USD', '$'),
('UA', 'Ukraine', 2, 'EUR', '€'),
('ZA', 'South Africa', 2, 'ZAR', 'R'),
('YE', 'Yemen', 2, 'USD', '$'),
('BY', 'Belarus', 2, 'EUR', '€'),
('GI', 'Gibraltar', 2, 'EUR', '€'),
('IQ', 'Iraq', 2, 'USD', '$'),
('OM', 'Oman', 2, 'USD', '$'),
('SI', 'Slovenia', 2, 'EUR', '€'),
('AM', 'Armenia', 2, 'USD', '$'),
('TR', 'Turkey', 2, 'TRY', '₺')
ON CONFLICT (country_code) DO UPDATE SET
    country_name = EXCLUDED.country_name,
    tier_level = EXCLUDED.tier_level,
    currency_code = EXCLUDED.currency_code,
    currency_symbol = EXCLUDED.currency_symbol,
    updated_at = CURRENT_TIMESTAMP;

-- TIER 3 - Developed Markets (15.99$ Pro / 23.99$ Elite)
-- Total: 15 countries
INSERT INTO stripe_country_tiers (country_code, country_name, tier_level, currency_code, currency_symbol) VALUES
('BE', 'Belgium', 3, 'EUR', '€'),
('FR', 'France', 3, 'EUR', '€'),
('AT', 'Austria', 3, 'EUR', '€'),
('FI', 'Finland', 3, 'EUR', '€'),
('IT', 'Italy', 3, 'EUR', '€'),
('PT', 'Portugal', 3, 'EUR', '€'),
('DK', 'Denmark', 3, 'DKK', 'kr'),
('NL', 'Netherlands', 3, 'EUR', '€'),
('DE', 'Germany', 3, 'EUR', '€'),
('KR', 'South Korea', 3, 'KRW', '₩'),
('SE', 'Sweden', 3, 'SEK', 'kr'),
('JP', 'Japan', 3, 'JPY', '¥'),
('NZ', 'New Zealand', 3, 'NZD', 'NZ$'),
('TW', 'Taiwan', 3, 'USD', '$'),
('ES', 'Spain', 3, 'EUR', '€')
ON CONFLICT (country_code) DO UPDATE SET
    country_name = EXCLUDED.country_name,
    tier_level = EXCLUDED.tier_level,
    currency_code = EXCLUDED.currency_code,
    currency_symbol = EXCLUDED.currency_symbol,
    updated_at = CURRENT_TIMESTAMP;

-- TIER 4 - Premium Markets (19.99$ Pro / 31.99$ Elite)
-- Total: 14 countries
INSERT INTO stripe_country_tiers (country_code, country_name, tier_level, currency_code, currency_symbol) VALUES
('AE', 'United Arab Emirates', 4, 'AED', 'د.إ'),
('US', 'United States', 4, 'USD', '$'),
('QA', 'Qatar', 4, 'QAR', 'QR'),
('IE', 'Ireland', 4, 'EUR', '€'),
('AU', 'Australia', 4, 'AUD', 'A$'),
('KW', 'Kuwait', 4, 'KWD', 'KD'),
('IS', 'Iceland', 4, 'EUR', '€'),
('CA', 'Canada', 4, 'CAD', 'CA$'),
('SG', 'Singapore', 4, 'SGD', 'S$'),
('HK', 'Hong Kong', 4, 'HKD', 'HK$'),
('LU', 'Luxembourg', 4, 'EUR', '€'),
('CH', 'Switzerland', 4, 'CHF', 'CHF'),
('NO', 'Norway', 4, 'NOK', 'kr'),
('GB', 'United Kingdom', 4, 'GBP', '£')
ON CONFLICT (country_code) DO UPDATE SET
    country_name = EXCLUDED.country_name,
    tier_level = EXCLUDED.tier_level,
    currency_code = EXCLUDED.currency_code,
    currency_symbol = EXCLUDED.currency_symbol,
    updated_at = CURRENT_TIMESTAMP;

-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================

-- Count countries by tier
SELECT tier_level, COUNT(*) as country_count
FROM stripe_country_tiers
WHERE active = TRUE
GROUP BY tier_level
ORDER BY tier_level;

-- Show sample countries from each tier
SELECT tier_level, country_code, country_name, currency_code
FROM stripe_country_tiers
WHERE active = TRUE
ORDER BY tier_level, country_name
LIMIT 20;
