name: intelia-expert-api
region: nyc1

services:
- name: api
  source_dir: /backend
  github:
    repo: dominicdesy/intelia-expert
    branch: main
    deploy_on_push: true
  
  # Utiliser buildpack Python
  environment_slug: python
  
  # Port correct pour FastAPI
  http_port: 8080
  
  # Commande pour démarrer l'application
  run_command: python -m app.main
  
  instance_count: 1
  instance_size_slug: basic-xxs
  
  health_check:
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 30
    timeout_seconds: 10
    success_threshold: 1
    failure_threshold: 3
  
  routes:
  - path: /
  
  # Variables d'environnement publiques
  envs:
  - key: PORT
    value: "8080"
  - key: ENVIRONMENT
    value: "production"
  - key: DEBUG
    value: "false"
  - key: LOG_LEVEL
    value: "INFO"
  - key: RAG_INDEX_PATH
    value: "/tmp/rag_index"
  - key: RAG_DOCUMENTS_PATH
    value: "/tmp/documents"
  - key: ALLOWED_ORIGINS
    value: "*"
  - key: PYTHONUNBUFFERED
    value: "1"
  
  # Secrets (à configurer dans l'interface DigitalOcean)
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: SECRET_KEY
    scope: RUN_TIME  
    type: SECRET

# Alertes pour monitoring
alerts:
- rule: CPU_UTILIZATION
  operator: GREATER_THAN
  value: 80
  window: FIVE_MINUTES
- rule: MEM_UTILIZATION
  operator: GREATER_THAN
  value: 80
  window: FIVE_MINUTES