# .do/app.yaml - Configuration optimisée Intelia Expert
name: intelia-expert
region: nyc3

services:
  # Backend FastAPI avec Dockerfile optimisé
  - name: intelia-expert-backend
    source_dir: /
    github:
      repo: your-username/intelia-expert  # ← Remplacez par votre repo
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile            # Utilise le Dockerfile à la racine
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
    envs:
      - key: PYTHONPATH
        value: /app
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
      - key: SUPABASE_URL
        value: ${SUPABASE_URL}
        type: SECRET
      - key: SUPABASE_KEY
        value: ${SUPABASE_KEY}
        type: SECRET
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
        type: SECRET

  # Frontend Next.js avec Dockerfile optimisé
  - name: intelia-expert-frontend
    source_dir: /frontend
    github:
      repo: your-username/intelia-expert  # ← Remplacez par votre repo
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile            # Utilise frontend/Dockerfile
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=4096"
      - key: NPM_CONFIG_CACHE
        value: "/tmp/.npm"
      - key: NEXT_PUBLIC_API_URL
        value: ${intelia-expert-backend.PUBLIC_URL}
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: ${SUPABASE_URL}
        type: SECRET
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: ${SUPABASE_ANON_KEY}
        type: SECRET

# Base de données PostgreSQL
databases:
  - name: db
    engine: PG
    version: "15"
    production: false
    size: basic

# Configuration des alertes de performance
alerts:
  - rule: CPU_UTILIZATION
    disabled: false
    operators:
      - type: GREATER_THAN
        value: 70
  - rule: MEM_UTILIZATION
    disabled: false
    operators:
      - type: GREATER_THAN
        value: 80