version: '3.8'

services:
  vllm:
    build:
      context: .
      dockerfile: Dockerfile
    image: intelia-vllm:latest
    container_name: intelia-vllm

    # GPU Configuration
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    # Environment Variables
    environment:
      # Model Configuration
      MODEL_NAME: "meta-llama/Llama-3.1-8B-Instruct"
      TENSOR_PARALLEL_SIZE: "1"  # Set to number of GPUs
      MAX_MODEL_LEN: "4096"
      GPU_MEMORY_UTILIZATION: "0.9"

      # HuggingFace Token (for gated models like Llama)
      HUGGING_FACE_HUB_TOKEN: "${HUGGINGFACE_API_KEY}"

      # Optional: Quantization for smaller memory footprint
      # QUANTIZATION: "awq"  # or "gptq" or "fp8"

    # Ports
    ports:
      - "8000:8000"

    # Health Check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      start_period: 120s
      retries: 3

    # Restart Policy
    restart: unless-stopped

    # Volumes (for model caching)
    volumes:
      - vllm-cache:/root/.cache/huggingface

    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  vllm-cache:
    driver: local
