# =============================================================================
# CONFIGURATION SECRETS COMPASS PROJECT
# =============================================================================
# Fichier : .streamlit/secrets.toml
# Configuration avec clés existantes intégrées et support RAG complet

# =============================================================================
# SERVICES IA (CLÉS EXISTANTES INTÉGRÉES)
# =============================================================================

# OpenAI API (CLÉS EXISTANTES)
openai_key = "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"

# Claude API (CLÉS EXISTANTES)
claude_key = "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"

# =============================================================================
# API COMPASS (CONFIGURATION EXISTANTE)
# =============================================================================

# Token d'accès API Compass existant
compass_token = "9256ef2476af4052b124342949658027"

# =============================================================================
# MICROSOFT GRAPH (CONFIGURATION EXISTANTE)
# =============================================================================

# Configuration Azure AD existante
microsoft_graph_tenant_id = "intelia.com"
microsoft_graph_client_id = "488b745d-e5c4-42b0-896b-a12eb9296b28"
microsoft_graph_client_secret = ".968Q~.5YOdbwpQxDYGneoFyq-.gfqGpEIKDRbDG"
microsoft_graph_from_email = "assistant@intelia.com"

# =============================================================================
# SERVICES MÉTÉO (CONFIGURATION EXISTANTE)
# =============================================================================

# WeatherAPI.com - clé existante
weather_api_key = "30c58b6512294ffe8b0230713250201"

# =============================================================================
# CHEMINS ET URLS (CONFIGURATION EXISTANTE WINDOWS)
# =============================================================================

# Chemins système Windows
RAG_INDEX_PATH = "C:/broiler_agent/rag_index"
COMPASS_API_BASE_URL = "https://compass.intelia.com/api/v1"

# =============================================================================
# CONFIGURATION RAG (NOUVEAU - RÉSOUT L'ERREUR EMBEDDING)
# =============================================================================

[rag]
# Méthode d'embedding - utiliser "OpenAI" avec clé existante
embedding_method = "OpenAI"

# Modèle pour embeddings OpenAI
model_name = "text-embedding-ada-002"

# Activer le système RAG
enabled = true

# Chemin vers l'index RAG (Windows)
index_path = "C:/broiler_agent/rag_index"

# Configuration avancée pour performance
chunk_size = 256
overlap = 64
max_results = 5
dimension = 1536

# Mode de fonctionnement (intégré avec existant)
mode = "fallback"
fallback_enabled = true
disable_warnings = false

# Debug et fallbacks
debug_mode = false
auto_detect_method = true
fallback_to_openai = true

# =============================================================================
# CONFIGURATION MICROSOFT GRAPH (FORMAT ALTERNATIF SUPPORTÉ)
# =============================================================================

[microsoft_graph]
tenant_id = "intelia.com"
client_id = "488b745d-e5c4-42b0-896b-a12eb9296b28"
client_secret = ".968Q~.5YOdbwpQxDYGneoFyq-.gfqGpEIKDRbDG"
from_email = "assistant@intelia.com"

# =============================================================================
# PARAMÈTRES ANALYSES (OPTIMISATION AVEC CLÉS EXISTANTES)
# =============================================================================

[analysis]
# Modèle par défaut pour analyses détaillées
default_model = "gpt-4o"

# Modèle pour summaries et tâches économiques
summary_model = "gpt-3.5-turbo"

# Modèle pour traductions
translation_model = "gpt-3.5-turbo"

# Activer l'analyse météo contextuelle
weather_enabled = true

# Activer le système RAG pour expertise
rag_enabled = true

[alerts]
# Configuration monitoring existante
interval_hours = 1
cooldown_hours = 4

# Seuils d'alerte optimisés pour Ross 308
temperature_high = 30.0
temperature_low = 18.0
humidity_high = 80.0
humidity_low = 45.0

# Utiliser RAG pour analyses d'alertes
rag_enhanced_alerts = true

[email]
# Configuration email existante
provider = "microsoft_graph"
retry_attempts = 3
timeout_seconds = 30

# Templates et langues supportées
supported_languages = ["en", "fr", "es"]
default_language = "fr"

[logging]
# Configuration logs existante
level = "INFO"
debug_mode = false

# Cache configuration existante
streamlit_cache_ttl = 3600
translation_cache_ttl = 600

# Logs spécifiques RAG
rag_debug = false
embedding_debug = false

# =============================================================================
# CONFIGURATION SYSTÈME (EXISTANTE)
# =============================================================================

# Système de log global
LOG_LEVEL = "INFO"

# Cache Streamlit
STREAMLIT_CACHE_TTL = 3600

# Mode RAG (configuration existante intégrée)
RAG_MODE = "fallback"
TRANSLATION_CACHE_TTL = 600
ENABLE_RAG_FALLBACK = true
DISABLE_RAG_WARNINGS = false

# =============================================================================
# NOTES DE CONFIGURATION
# =============================================================================
# 1. Cette configuration utilise TOUTES les clés existantes du projet
# 2. Résout l'erreur "Unknown embedding method: sentence_transformers"
# 3. Utilise OpenAI embeddings avec la clé existante pour performance optimale
# 4. Maintient la compatibilité complète avec l'architecture Windows existante
# 5. Préserve tous les paramètres de cache et de logging existants
# 6. Compatible avec tous les services existants (Compass, Microsoft Graph, Weather)
